apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k6-results-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
spec:
  template:
    metadata:
      labels:
        egress-frontoffice-policy: allow
        ingress-controller-frontoffice-policy: allow
        tier: vertrouwd
    spec:
      containers:
      - name: k6
        image: loadimpact/k6:latest
        command: ["k6", "run", "/scripts/example.js"]
        env:
        - name: BASE_URL
          value: "http://profiel-service-service.logius-moz-poc.svc.cluster.local:8080"
        volumeMounts:
        - name: k6-script-volume
          mountPath: /scripts
        - name: k6-results-volume
          mountPath: /results
      restartPolicy: Never
      volumes:
      - name: k6-script-volume
        configMap:
          name: k6-test-script
      - name: k6-results-volume
        persistentVolumeClaim:
          claimName: k6-results-pvc
  backoffLimit: 1
