# OpenAPI Generator
# Basisprofiel API Client
quarkus.openapi-generator.codegen.spec.api_basisprofiel_yaml.base-package=nl.rijksoverheid.moz.external.clients.basisprofiel
quarkus.openapi-generator.codegen.spec.api_basisprofiel_yaml.config-key=basisprofiel-api
# Email Verificatie Client
quarkus.openapi-generator.codegen.spec.verificatie_service_yaml.base-package=nl.rijksoverheid.moz.external.clients.verificatie_service
quarkus.openapi-generator.codegen.spec.verificatie_service_yaml.config-key=verificatie-service
# Client URLs
quarkus.rest-client.basisprofiel-api.url=TODO
quarkus.rest-client.verificatie-service.url=internal-verificatie-service:8080


# Database
# Do not use this in production
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%prod.quarkus.hibernate-orm.schema-management.strategy=update

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.max-size=16
quarkus.datasource.username=user
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/profiel
# Override for production - values will come from the secret
%prod.quarkus.datasource.jdbc.url=
%prod.quarkus.datasource.username=
%prod.quarkus.datasource.password=

#LDV properties
logboekdataverwerking.enabled=true
logboekdataverwerking.service-name=profiel-service
logboekdataverwerking.clickhouse.endpoint=http://localhost:8123
logboekdataverwerking.clickhouse.username=user
logboekdataverwerking.clickhouse.password=password
logboekdataverwerking.clickhouse.database=ldv_logging
logboekdataverwerking.clickhouse.table=logging
# Override for production - values will come from the secret
%prod.logboekdataverwerking.enabled=
%prod.logboekdataverwerking.service-name=
%prod.logboekdataverwerking.clickhouse.endpoint=
%prod.logboekdataverwerking.clickhouse.username=
%prod.logboekdataverwerking.clickhouse.password=
%prod.logboekdataverwerking.clickhouse.database=
%prod.logboekdataverwerking.clickhouse.table=

#NotifyNL properties
notifynl.emailverificatie.api-key=Zie-readme
notifynl.emailverificatie.template-id=Zie-readme
notifynl.emailverificatie.reference=Zie-readme
%prod.notifynl.emailverificatie.api-key=
%prod.notifynl.emailverificatie.template-id=
%prod.notifynl.emailverificatie.reference=

# Tests
quarkus.jacoco.excludes=nl/rijksoverheid/moz/external/**
