## Openapi
#quarkus.openapi.generator.spec=profielservice.yaml
#quarkus.openapi.generator.base-package=nl.rijksoverheid.moz
#quarkus.openapi.generator.reactive=false

# Basisprofiel API Client
quarkus.openapi-generator.codegen.spec.api_basisprofiel_yaml.base-package=nl.rijksoverheid.moz.external.clients.basisprofiel
quarkus.openapi-generator.codegen.spec.api_basisprofiel_yaml.config-key=basisprofiel-api

# Email Verificatie Client
quarkus.openapi-generator.codegen.spec.email_verificatie_json.base-package=nl.rijksoverheid.moz.external.clients.email
quarkus.openapi-generator.codegen.spec.email_verificatie_json.config-key=email-api

# Client URLs
quarkus.rest-client.basisprofiel-api.url=TODO
quarkus.rest-client.email-api.url=TODO

# zie docker-compose file in root van project
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/profiel
quarkus.datasource.jdbc.max-size=16

#do not use this in production
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

#%prod.quarkus.kubernetes-config.secrets.enabled=true

#%prod.quarkus.kubernetes-config.secrets=secret-name
%prod.quarkus.datasource.jdbc.url=
%prod.quarkus.datasource.username=
%prod.quarkus.datasource.password=

#TODO dit moet de migration tool voor je doen
%prod.quarkus.hibernate-orm.schema-management.strategy=update


#LDV properties
logboekdataverwerking.service-name=profiel-service
logboekdataverwerking.clickhouse.endpoint=jdbc:clickhouse://localhost:8123
logboekdataverwerking.clickhouse.username=ldv_user
logboekdataverwerking.clickhouse.password=password
logboekdataverwerking.clickhouse.database=ldv_logging
logboekdataverwerking.clickhouse.table=logging

# Quarkus Deployment
quarkus.container-image.image=
quarkus.container-image.username=
quarkus.container-image.password=
quarkus.container-image.build=true
quarkus.container-image.push=true
quarkus.container-image.insecure=false
quarkus.container-image.builder=jib
quarkus.kubernetes.image-pull-secrets=harbor-puller
quarkus.kubernetes.labels.egress-frontoffice-policy=allow
quarkus.kubernetes.labels.ingress-controller-frontoffice-policy=allow
quarkus.kubernetes.labels.access-to-connectionpool=allow
quarkus.kubernetes.labels.tier=vertrouwd
quarkus.kubernetes.ingress.expose=true
quarkus.kubernetes.ingress.enabled=true
quarkus.kubernetes.ingress.tls.enabled=true
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger

quarkus.kubernetes.ingress.host=profiel.mijnoverheidzakelijk.nl
quarkus.kubernetes.ingress.tls[0].hosts=profiel.mijnoverheidzakelijk.nl
quarkus.kubernetes.ingress.tls[0].secret-name=mijnoverheidzakelijk-tls
quarkus.kubernetes.ingress.ingress-class-name=nginx
quarkus.kubernetes.ports.http.host-port=8080
quarkus.kubernetes.ingress.annotations."odcn.rijksapps.nl/inet-loadbalancer-hostnames"=profiel.mijnoverheidzakelijk.nl
quarkus.kubernetes.ingress.labels."odcn.rijksapps.nl/inet-loadbalancer"=" "

quarkus.kubernetes.resources.requests.memory=64Mi
quarkus.kubernetes.resources.requests.cpu=250m
quarkus.kubernetes.resources.limits.memory=512Mi
quarkus.kubernetes.resources.limits.cpu=1000m

quarkus.kubernetes.service-account=sp-nonroot
quarkus.kubernetes-client.generate-rbac=false
quarkus.kubernetes.name=profiel-service